// KAI-191 follow-up — codegen for the admin_users role CHECK constraint.
//
// ADMIN_ROLES (packages/types/src/admin.ts) is the single source of truth
// for the Kelan backoffice role vocabulary. `admin_users_role_check` in the
// database enumerates the same values by hand in SQL, written independently
// of the TypeScript array. Postgres cannot import a TypeScript module, so
// nothing stops the two from drifting if a future migration edits one list
// without the other.
//
// This file generates the exact CHECK-constraint fragment Postgres emits
// (via `supabase db dump`) into supabase/schema.sql, in the same quoting
// style already used there (`'admin'::"text"`). It is not run at
// migration-apply time — schema.sql is generated by the Supabase CLI, never
// hand-edited. admin-role-check-sql.test.ts regenerates this fragment from
// the current ADMIN_ROLES on every test run and asserts supabase/schema.sql
// still contains it verbatim, so a change to ADMIN_ROLES that isn't matched
// by a migration (and a fresh `supabase db dump`) fails the test suite
// instead of silently drifting.
import { ADMIN_ROLES } from "@kairo/types";

/** `admin_users.role` — admin_users_role_check. NOT NULL, no null branch. */
export function generateAdminUsersRoleCheckSql(): string {
  const values = ADMIN_ROLES.map((role) => `'${role}'::"text"`).join(", ");
  return `CONSTRAINT "admin_users_role_check" CHECK (("role" = ANY (ARRAY[${values}])))`;
}
