// ---------------------------------------------------------------------------
// KAI-45 F6 — the classification pipeline's decisions, as OpenTelemetry spans.
//
// Until now `apps/api` emitted no span of its own: the only instrumentation was
// the HTTP middleware in index.ts. The routing decision, the tenant context the
// classifier was given, whether a proposal auto-approved and why, and a
// person's correction were all invisible in ClickStack, and every degradation
// F3–F5 added was a `console.warn` — which reaches no backend, because
// packages/observability/src/node.ts exports traces only.
//
// One span per decision, ended as soon as it is made: the decisions are pure
// and take no time, so the span is a record, not a measurement. Each opens under
// whatever span is active — the HTTP request, the Inngest step — so it sits in
// the trace of the work that made it.
//
// Attribute builders are separate, pure functions so what reaches ClickStack is
// testable without a collector. No address, domain or message text goes in an
// attribute: provenance is a three-value enum, and the rest are flags, counts
// and versions.
//
// A no-op when OTEL_EXPORTER_OTLP_ENDPOINT is unset (docs/observability.md,
// step 5): with no SDK registered, the API hands back a tracer that records
// nothing.
// ---------------------------------------------------------------------------

import { trace, type Attributes } from "@opentelemetry/api";
import { provenanceOf, type TicketType } from "@kairo/intelligence";

import type { ClassifierContext, ClassifierStage } from "./classifier-input.js";
import type { MailFacts } from "./email/mail-facts.js";
import { ROUTING_POLICY_VERSION, type Route } from "./email/routing-policy.js";

const tracer = trace.getTracer("kairo-api");

export interface DecisionEvent {
  name: string;
  attributes?: Attributes;
}

/** Records a decision already made, as a span that opens and closes at once. */
export function recordDecision(name: string, attributes: Attributes, events: DecisionEvent[] = []): void {
  const span = tracer.startSpan(name, { attributes });
  for (const event of events) span.addEvent(event.name, event.attributes);
  span.end();
}

/** `email.route` — the routing policy's decision and the facts it read. */
export function routeAttributes(facts: MailFacts, route: Route): Attributes {
  return {
    "kairo.routing.policy_version": ROUTING_POLICY_VERSION,
    "kairo.routing.route": route.kind,
    ...(route.kind === "skip" ? { "kairo.routing.skip_reason": route.reason } : {}),
    "kairo.routing.signals": route.signals,
    "kairo.mail.provenance": provenanceOf(facts),
    "kairo.mail.tenant_domain_is_public": facts.tenantDomainIsPublic,
    "kairo.mail.tenant_in_recipients": facts.tenantInRecipients,
    "kairo.mail.recipient_count": facts.recipientCount,
    "kairo.mail.is_automated_sender": facts.isAutomatedSender,
    "kairo.mail.has_list_unsubscribe": facts.hasListUnsubscribe,
    "kairo.mail.is_auto_generated": facts.isAutoGenerated,
    "kairo.mail.is_auto_submitted": facts.isAutoSubmitted,
    "kairo.mail.is_bulk": facts.isBulk,
    "kairo.mail.is_reply": facts.isReply,
    "kairo.mail.references_count": facts.referencesCount,
    // null means the provider gave no verdict, which is not the same as a
    // clean one; the attribute is left out rather than written as false.
    ...(facts.spamFiltered !== null ? { "kairo.mail.spam_filtered": facts.spamFiltered } : {}),
    ...(facts.spamScore !== null ? { "kairo.mail.spam_score": facts.spamScore } : {}),
    ...(facts.authResult !== null ? { "kairo.mail.auth_result": facts.authResult } : {}),
    ...(facts.gmailCategory !== null ? { "kairo.mail.gmail_category": facts.gmailCategory } : {}),
    "kairo.mail.is_calendar_invite": facts.isCalendarInvite,
    "kairo.mail.has_system_subject_prefix": facts.hasSystemSubjectPrefix,
    "kairo.mail.has_urgency_keyword": facts.hasUrgencyKeyword,
  };
}

/**
 * Why the tenant context came back less than complete. Each one used to be a
 * `console.warn` and nothing else; each is now an event on `classifier.context`.
 */
export type ContextDegradation =
  | "support_channels_unreadable"
  | "accounts_unreadable"
  | "unsupported_language";

/** `classifier.context` — what the classifier is handed for this account. */
export function classifierContextAttributes(
  stage: ClassifierStage,
  accountId: string,
  context: ClassifierContext,
): Attributes {
  return {
    "kairo.account_id": accountId,
    "kairo.classifier.stage": stage,
    "kairo.classifier.language": context.language,
    "kairo.classifier.mailbox_count": context.tenantMailboxes.length,
    "kairo.classifier.has_business_context": context.businessContext !== undefined,
  };
}

/**
 * Which rule decided a proposal's status. The first one that applies wins, in
 * the order the status functions check them.
 */
export type ProposalStatusReason =
  | "abstain"
  | "support"
  | "not_support"
  | "no_business_context"
  | "auto_approval_earned"
  | "auto_approval_not_earned";

/** `ticket.proposal_status` — whether a classification stands on its own, and why. */
export function proposalStatusAttributes(input: {
  stage: ClassifierStage;
  type: TicketType;
  status: "auto_approved" | "pending";
  reason: ProposalStatusReason;
}): Attributes {
  return {
    "kairo.proposal.stage": input.stage,
    "kairo.proposal.type": input.type,
    "kairo.proposal.status": input.status,
    "kairo.proposal.reason": input.reason,
  };
}

/** `ticket.correction` — a person replacing the type the pipeline produced. */
export function correctionAttributes(input: {
  ticketId: string;
  accountId: string;
  from: string;
  to: string;
  derivationVersion: string | null;
  promptVersion: string | null;
  routingPolicyVersion: string | null;
}): Attributes {
  return {
    "kairo.ticket_id": input.ticketId,
    "kairo.account_id": input.accountId,
    "kairo.correction.from_type": input.from,
    "kairo.correction.to_type": input.to,
    ...(input.derivationVersion ? { "kairo.correction.derivation_version": input.derivationVersion } : {}),
    ...(input.promptVersion ? { "kairo.correction.prompt_version": input.promptVersion } : {}),
    ...(input.routingPolicyVersion ? { "kairo.correction.routing_policy_version": input.routingPolicyVersion } : {}),
  };
}
