// KAI-191 — codegen for the ticket status CHECK constraints.
//
// TICKET_STATUSES (packages/types/src/index.ts) is the single source of
// truth for the ticket status vocabulary. Three CHECK constraints in the
// database — `tickets_status_check`, `ticket_state_history_from_state_check`
// and `ticket_state_history_to_state_check` — enumerate that same vocabulary
// by hand in SQL, written independently of the TypeScript union. Postgres
// cannot import a TypeScript module, so nothing stops the two from drifting
// if a future migration edits one list without the other.
//
// This file generates the exact CHECK-constraint fragments Postgres emits
// (via `supabase db dump`) into supabase/schema.sql, in the same quoting
// style already used there (`'open'::"text"`). It is not run at
// migration-apply time — schema.sql is generated by the Supabase CLI, never
// hand-edited. ticket-status-check-sql.test.ts regenerates these fragments
// from the current TICKET_STATUSES on every test run and asserts
// supabase/schema.sql still contains them verbatim, so a change to
// TICKET_STATUSES that isn't matched by a migration (and a fresh
// `supabase db dump`) fails the test suite instead of silently drifting.
import { TICKET_STATUSES } from "@kairo/types";

/**
 * The `ARRAY['open'::"text", 'awaiting_customer'::"text", ...]` fragment
 * shared by all three status CHECK constraints, in schema.sql's quoting
 * style.
 */
export function generateStatusArraySql(): string {
  const values = TICKET_STATUSES.map((status) => `'${status}'::"text"`).join(", ");
  return `ARRAY[${values}]`;
}

/** The `tickets.status` CHECK constraint, as emitted into schema.sql. */
export function generateTicketsStatusCheckSql(): string {
  return `CONSTRAINT "tickets_status_check" CHECK (("status" = ANY (${generateStatusArraySql()})))`;
}

/**
 * The `ticket_state_history.to_state` CHECK constraint, as emitted into
 * schema.sql.
 */
export function generateTicketStateHistoryToStateCheckSql(): string {
  return `CONSTRAINT "ticket_state_history_to_state_check" CHECK (("to_state" = ANY (${generateStatusArraySql()})))`;
}

/**
 * The `ticket_state_history.from_state` CHECK constraint, as emitted into
 * schema.sql. `from_state` is nullable (a ticket's first history row has no
 * prior state), so this one also allows NULL.
 */
export function generateTicketStateHistoryFromStateCheckSql(): string {
  return `CONSTRAINT "ticket_state_history_from_state_check" CHECK ((("from_state" IS NULL) OR ("from_state" = ANY (${generateStatusArraySql()}))))`;
}
