// KAI-191 follow-up — codegen for the ticket classification CHECK
// constraints (ticket_type, priority, category, tone).
//
// TICKET_TYPES / TICKET_PRIORITIES / TICKET_CATEGORIES / TICKET_TONES
// (packages/types/src/classification.ts) are the single source of truth for
// this vocabulary. Six CHECK constraints across three tables enumerate the
// same values by hand in SQL, written independently of the TypeScript
// arrays. Postgres cannot import a TypeScript module, so nothing stops the
// two from drifting if a future migration edits one list without the other.
//
// This file generates the exact CHECK-constraint fragments Postgres emits
// (via `supabase db dump`) into supabase/schema.sql, in the same quoting
// style already used there (`'support'::"text"`). It is not run at
// migration-apply time — schema.sql is generated by the Supabase CLI, never
// hand-edited. ticket-classification-check-sql.test.ts regenerates these
// fragments from the current arrays on every test run and asserts
// supabase/schema.sql still contains them verbatim, so a change to one of
// the four arrays that isn't matched by a migration (and a fresh
// `supabase db dump`) fails the test suite instead of silently drifting.
import { TICKET_TYPES, TICKET_PRIORITIES, TICKET_CATEGORIES, TICKET_TONES } from "@kairo/types";

function arraySql(values: readonly string[]): string {
  return `ARRAY[${values.map((v) => `'${v}'::"text"`).join(", ")}]`;
}

/** `tickets.ticket_type` — chk_ticket_type. Nullable. */
export function generateTicketsTicketTypeCheckSql(): string {
  return `CONSTRAINT "chk_ticket_type" CHECK ((("ticket_type" IS NULL) OR ("ticket_type" = ANY (${arraySql(TICKET_TYPES)}))))`;
}

/** `tickets.priority` — chk_priority. Nullable. */
export function generateTicketsPriorityCheckSql(): string {
  return `CONSTRAINT "chk_priority" CHECK ((("priority" IS NULL) OR ("priority" = ANY (${arraySql(TICKET_PRIORITIES)}))))`;
}

/** `tickets.category` — chk_category. Nullable. */
export function generateTicketsCategoryCheckSql(): string {
  return `CONSTRAINT "chk_category" CHECK ((("category" IS NULL) OR ("category" = ANY (${arraySql(TICKET_CATEGORIES)}))))`;
}

/** `tickets.emotion` — chk_emotion. Nullable. Shares TICKET_TONES with sentiment below. */
export function generateTicketsEmotionCheckSql(): string {
  return `CONSTRAINT "chk_emotion" CHECK ((("emotion" IS NULL) OR ("emotion" = ANY (${arraySql(TICKET_TONES)}))))`;
}

/** `tickets.sentiment` — chk_sentiment. Nullable. Shares TICKET_TONES with emotion above. */
export function generateTicketsSentimentCheckSql(): string {
  return `CONSTRAINT "chk_sentiment" CHECK ((("sentiment" IS NULL) OR ("sentiment" = ANY (${arraySql(TICKET_TONES)}))))`;
}

/** `ticket_type_auto_approval.ticket_type` — chk_tta_ticket_type. NOT NULL, no null branch. */
export function generateTicketTypeAutoApprovalCheckSql(): string {
  return `CONSTRAINT "chk_tta_ticket_type" CHECK (("ticket_type" = ANY (${arraySql(TICKET_TYPES)})))`;
}

/** `ticket_proposals.proposed_emotion` — chk_proposed_emotion. Nullable. */
export function generateTicketProposalsProposedEmotionCheckSql(): string {
  return `CONSTRAINT "chk_proposed_emotion" CHECK ((("proposed_emotion" IS NULL) OR ("proposed_emotion" = ANY (${arraySql(TICKET_TONES)}))))`;
}
