-- KAI-191 — ticket_transition_rules + apply_ticket_transition.
--
-- tickets.status is currently written from five different places in
-- apps/api, three of which separately re-implement the same validation
-- against ALLOWED_TRANSITIONS (apps/api/src/lib/ticket-status-machine.ts).
-- None of them owns the column, and ticket_state_history (created by
-- 20260831161357_create_ticket_state_history.sql) is written by nobody yet.
--
-- This migration makes apply_ticket_transition() the single place that can
-- move tickets.status, and makes the tickets.status update + the
-- ticket_state_history insert atomic (one transaction), so the trail can
-- never fall behind the column it is supposed to explain.
--
-- Postgres cannot import ALLOWED_TRANSITIONS from TypeScript, so it is
-- mirrored into ticket_transition_rules, a plain data table seeded by the
-- generated INSERT block below. apps/api/src/lib/ticket-transition-rules-sql.ts
-- generates that block from ALLOWED_TRANSITIONS, and
-- ticket-transition-rules-sql.test.ts re-generates it on every test run and
-- asserts it still matches this file byte for byte — the two can never
-- silently diverge.

-- ─────────────────────────────────────────────────────────────────────────────
-- ticket_transition_rules — mirrors ALLOWED_TRANSITIONS. Never hand-edit the
-- seed data below; regenerate it with ticket-transition-rules-sql.ts.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "public"."ticket_transition_rules" (
    "from_state" "text" NOT NULL,
    "to_state" "text" NOT NULL,
    CONSTRAINT "ticket_transition_rules_pkey" PRIMARY KEY ("from_state", "to_state"),
    CONSTRAINT "ticket_transition_rules_from_state_check" CHECK (("from_state" = ANY (ARRAY['open'::"text", 'awaiting_customer'::"text", 'in_progress'::"text", 'resolved'::"text", 'ai_resolved'::"text", 'escalated'::"text", 'reopened'::"text", 'closed'::"text"]))),
    CONSTRAINT "ticket_transition_rules_to_state_check" CHECK (("to_state" = ANY (ARRAY['open'::"text", 'awaiting_customer'::"text", 'in_progress'::"text", 'resolved'::"text", 'ai_resolved'::"text", 'escalated'::"text", 'reopened'::"text", 'closed'::"text"])))
);

ALTER TABLE "public"."ticket_transition_rules" OWNER TO "postgres";

COMMENT ON TABLE "public"."ticket_transition_rules" IS 'Mirrors ALLOWED_TRANSITIONS from apps/api/src/lib/ticket-status-machine.ts. Generated by apps/api/src/lib/ticket-transition-rules-sql.ts — never hand-edited. Read by apply_ticket_transition(); ticket-transition-rules-sql.test.ts asserts this seed stays byte-for-byte in sync with the TypeScript table.';

ALTER TABLE "public"."ticket_transition_rules" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "ticket_transition_rules_select_all" ON "public"."ticket_transition_rules" FOR SELECT USING (true);

GRANT SELECT ON TABLE "public"."ticket_transition_rules" TO "anon";
GRANT SELECT ON TABLE "public"."ticket_transition_rules" TO "authenticated";
GRANT ALL ON TABLE "public"."ticket_transition_rules" TO "service_role";

-- BEGIN GENERATED FROM apps/api/src/lib/ticket-status-machine.ts ALLOWED_TRANSITIONS (see apps/api/src/lib/ticket-transition-rules-sql.ts)
INSERT INTO public.ticket_transition_rules (from_state, to_state) VALUES
  ('open', 'awaiting_customer'),
  ('open', 'in_progress'),
  ('open', 'resolved'),
  ('open', 'escalated'),
  ('open', 'ai_resolved'),
  ('awaiting_customer', 'open'),
  ('awaiting_customer', 'resolved'),
  ('awaiting_customer', 'escalated'),
  ('in_progress', 'open'),
  ('in_progress', 'awaiting_customer'),
  ('in_progress', 'resolved'),
  ('in_progress', 'escalated'),
  ('resolved', 'open'),
  ('resolved', 'reopened'),
  ('resolved', 'closed'),
  ('ai_resolved', 'open'),
  ('ai_resolved', 'reopened'),
  ('ai_resolved', 'closed'),
  ('escalated', 'resolved'),
  ('escalated', 'open'),
  ('escalated', 'reopened'),
  ('reopened', 'in_progress'),
  ('reopened', 'resolved'),
  ('reopened', 'escalated'),
  ('reopened', 'awaiting_customer');
-- END GENERATED

-- ─────────────────────────────────────────────────────────────────────────────
-- apply_ticket_transition — the only writer of tickets.status.
--
-- Outcomes:
--   * ticket not found          → RAISE EXCEPTION, ERRCODE 'KA404'
--   * illegal transition        → RAISE EXCEPTION, ERRCODE 'KA409'
--   * from_state = to_state     → returns one row, outcome = 'no_op' (not an error)
--   * idempotency_key conflict  → returns one row, outcome = 'no_op' (not an error)
--   * otherwise                 → returns one row, outcome = 'applied'
--
-- The tickets.status UPDATE and the ticket_state_history INSERT happen in the
-- same statement-level transaction as everything else in this function body,
-- so they can never partially apply. The ticket row is locked FOR UPDATE for
-- the duration so two concurrent transitions on the same ticket serialize
-- instead of racing.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION "public"."apply_ticket_transition"(
    "p_ticket_id" "uuid",
    "p_to_state" "text",
    "p_actor_type" "text",
    "p_actor_user_id" "uuid",
    "p_actor_ref" "text",
    "p_trigger" "text",
    "p_reason" "text",
    "p_metadata" "jsonb",
    "p_idempotency_key" "text"
) RETURNS TABLE("outcome" "text", "from_state" "text", "to_state" "text", "history_id" "uuid")
    LANGUAGE "plpgsql"
    SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_from_state text;
  v_account_id uuid;
  v_history_id uuid;
BEGIN
  SELECT t.status, t.account_id
    INTO v_from_state, v_account_id
  FROM public.tickets t
  WHERE t.id = p_ticket_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'apply_ticket_transition: ticket % not found', p_ticket_id
      USING ERRCODE = 'KA404';
  END IF;

  -- Same-state request: no-op, not an error. Covers both a caller asking to
  -- move into the state the ticket is already in, and idempotency_key retries
  -- landing on the same target.
  IF v_from_state IS NOT DISTINCT FROM p_to_state THEN
    RETURN QUERY SELECT 'no_op'::text, v_from_state, p_to_state, NULL::uuid;
    RETURN;
  END IF;

  -- v_from_state = NULL only for a brand-new ticket recording its creation
  -- row (from_state NULL, to_state 'open') — that transition has no rule to
  -- look up and is always legal. Every other from_state must be validated.
  IF v_from_state IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM public.ticket_transition_rules r
    WHERE r.from_state = v_from_state
      AND r.to_state = p_to_state
  ) THEN
    RAISE EXCEPTION 'apply_ticket_transition: illegal transition from % to % for ticket %', v_from_state, p_to_state, p_ticket_id
      USING ERRCODE = 'KA409';
  END IF;

  UPDATE public.tickets
     SET status = p_to_state
   WHERE id = p_ticket_id;

  INSERT INTO public.ticket_state_history (
    account_id, ticket_id, from_state, to_state, actor_type, actor_user_id,
    actor_ref, trigger, reason, occurred_at, metadata, idempotency_key
  ) VALUES (
    v_account_id, p_ticket_id, v_from_state, p_to_state, p_actor_type, p_actor_user_id,
    p_actor_ref, p_trigger, p_reason, now(), p_metadata, p_idempotency_key
  )
  ON CONFLICT ON CONSTRAINT ticket_state_history_account_id_idempotency_key_key DO NOTHING
  RETURNING id INTO v_history_id;

  IF v_history_id IS NULL THEN
    -- Only reachable when p_idempotency_key was non-null and already recorded
    -- (the unique constraint ignores NULL idempotency_key entirely). The
    -- status UPDATE above still ran, but it applied the same value another
    -- request already committed, so treat this as a no-op rather than raise.
    RETURN QUERY SELECT 'no_op'::text, v_from_state, p_to_state, NULL::uuid;
    RETURN;
  END IF;

  RETURN QUERY SELECT 'applied'::text, v_from_state, p_to_state, v_history_id;
END;
$$;

ALTER FUNCTION "public"."apply_ticket_transition"("uuid", "text", "text", "uuid", "text", "text", "text", "jsonb", "text") OWNER TO "postgres";

REVOKE ALL ON FUNCTION "public"."apply_ticket_transition"("uuid", "text", "text", "uuid", "text", "text", "text", "jsonb", "text") FROM PUBLIC;
GRANT EXECUTE ON FUNCTION "public"."apply_ticket_transition"("uuid", "text", "text", "uuid", "text", "text", "text", "jsonb", "text") TO "service_role";

-- ─────────────────────────────────────────────────────────────────────────────
-- True append-only: raise on UPDATE/DELETE of ticket_state_history regardless
-- of role. RLS already blocks these for the browser (SELECT+INSERT-only
-- policies), but the API runs as service_role, which bypasses RLS entirely —
-- without this trigger the trail would only be append-only for the browser.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION "public"."reject_ticket_state_history_mutation"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  RAISE EXCEPTION 'ticket_state_history is append-only: % is not allowed', TG_OP
    USING ERRCODE = 'insufficient_privilege';
END;
$$;

ALTER FUNCTION "public"."reject_ticket_state_history_mutation"() OWNER TO "postgres";

CREATE TRIGGER "ticket_state_history_append_only"
    BEFORE UPDATE OR DELETE ON "public"."ticket_state_history"
    FOR EACH ROW EXECUTE FUNCTION "public"."reject_ticket_state_history_mutation"();
